<a href="https://colab.research.google.com/github/zakiapranti/Machine_Learning/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Example**

In [84]:
import numpy as np

In [85]:
a=np.arange(15).reshape(3,5) #0 theke 14 obdi digits niye  3x5 matrix
b=np.array([6,7,8])

In [86]:
a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
b

array([6, 7, 8])

In [ ]:
a.shape


(3, 5)

In [ ]:
b.shape

(3,)

In [ ]:
a.ndim

2

In [ ]:
b.ndim

1

In [ ]:
a.dtype.name
#a.dtype=same thing

'int64'

In [ ]:
b.dtype.name

'int64'

In [ ]:
a.itemsize

8

In [ ]:
a.size

15

In [ ]:
b.size

3

In [ ]:
type(a)

numpy.ndarray

In [ ]:
type (b)

numpy.ndarray

**Array** **Creation**

In [2]:
import numpy as np
a=np.array([2,3,4])

In [ ]:
a


array([2, 3, 4])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
b=np.array([1.2,3.5,6.7])

In [ ]:
b.dtype

dtype('float64')

*A frequent error consists in calling array with multiple arguments, rather than providing a single sequence as an argument.*

In [ ]:
a = np.array([1, 2, 3, 4])  # RIGHT
#a = np.array(1, 2, 3, 4)    # WRONG

*array transforms sequences of sequences into two-dimensional arrays,*

In [ ]:
b= np.array([(1.5,2,3,4),(3,4,5,6),(5,3,4,5.3)]) #2d array
#b=np.array([(array1),(array2),(array3)])

In [ ]:
b

array([[1.5, 2. , 3. , 4. ],
       [3. , 4. , 5. , 6. ],
       [5. , 3. , 4. , 5.3]])

*The type of the array can also be explicitly specified at creation time*

In [ ]:
c=np.array([(1,2),(3,5)],dtype=complex)
#can be written by the following way
##c=np.array([[1,2],[3,5]],dtype=complex)

In [ ]:
c


array([[1.+0.j, 2.+0.j],
       [3.+0.j, 5.+0.j]])

**Printing Arrays**

In [3]:
#1D array
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


In [5]:
a=np.array([2,3,4,5])
a

array([2, 3, 4, 5])

In [7]:
#2D Array
b=np.arange(12).reshape(3,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [8]:
#3D ARRAY
c=np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


#SHAPE MANIPULATION
#reshape() is used


In [12]:
rg = np.random.default_rng(1)
  # create instance of default random number generator
a=np.floor(10 * rg.random((3,4)))
a

array([[5., 9., 1., 9.],
       [3., 4., 8., 4.],
       [5., 0., 7., 5.]])

In [13]:
a.shape

(3, 4)

In [14]:
a.T

array([[5., 3., 5.],
       [9., 4., 0.],
       [1., 8., 7.],
       [9., 4., 5.]])

In [15]:
a.T.shape

(4, 3)

In [16]:
a.ravel()

array([5., 9., 1., 9., 3., 4., 8., 4., 5., 0., 7., 5.])

In [26]:
a.reshape(2,6) #shape modified kore

array([[5., 9., 1., 9., 3., 4.],
       [8., 4., 5., 0., 7., 5.]])

In [27]:
a.resize((6,2)) #mainn array ke change kore fele
a

array([[5., 9.],
       [1., 9.],
       [3., 4.],
       [8., 4.],
       [5., 0.],
       [7., 5.]])

In [20]:
a.reshape(3,-1)

array([[5., 9., 1., 9.],
       [3., 4., 8., 4.],
       [5., 0., 7., 5.]])

In [ ]:
np.arange(1000)
#choto size er array purata print hobe

In [33]:
np.arange(10000)
#size boro hoye gele automatically majher part skip kore
#boro size array er only corner parts dekhay

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [34]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


To disable this behaviour and force NumPy to print the entire array, you can change the printing options using **set_printoptions**.

In [38]:
from numpy import  sys
np.set_printoptions(threshold=sys.maxsize)  # sys module should be imported

In [ ]:
print(np.arange(10000).reshape(100,100))
#ei code ekhon runn dile purata matrix dekhbe

#array operations

In [40]:
a=np.array([2,3,4,5])
b=np.arange(4)
c=a-b
print(c)

[2 2 2 2]


In [41]:
b**2

array([0, 1, 4, 9])

In [42]:
10*np.sin(a)

array([ 9.09297427,  1.41120008, -7.56802495, -9.58924275])

In [43]:
np.sin(a)

array([ 0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [47]:
a=np.array([2,3,4,5])
a<4

array([ True,  True, False, False])

#product operator (* ,@, .dot())

In [49]:
A=np.array([[1,2],
            [3,4]
            ])
B=np.array([[2,4],
            [2,3]
            ])


In [50]:
#MATRIX PROD
A@B


array([[ 6, 10],
       [14, 24]])

In [51]:
#ELEMENTWISE PROD
A*B

array([[ 2,  8],
       [ 6, 12]])

In [53]:
# MATRIX PROD
#--> ebhabeo kora jabe
A.dot(B)

array([[ 6, 10],
       [14, 24]])

*modify* an existing array rather than create a new one.



 most recent value of a will be **updated**

In [73]:
rg=np.random.default_rng(1)
#create instance of default random number generator
a=np.ones((2,3), dtype=int)
b=rg.random((2,3))
a *= 3
a


array([[3, 3, 3],
       [3, 3, 3]])

In [74]:
a += 4
a


array([[7, 7, 7],
       [7, 7, 7]])

In [75]:
a*=2
a

array([[14, 14, 14],
       [14, 14, 14]])

In [76]:
b+=a
b

array([[14.51182162, 14.9504637 , 14.14415961],
       [14.94864945, 14.31183145, 14.42332645]])

In [77]:
#sorting arrays
a=np.array([2,3,4,1,2,1,3])
np.sort(a)


array([1, 1, 2, 2, 3, 3, 4])

# **vector stacking **

How do we construct a 2D array from a list of equally-sized row vectors?
 In NumPy this works via the functions column_stack, dstack, hstack and vstack, depending on the dimension in which the stacking is to be done.

In [82]:
x=np.array([2,3,4])
y=np.array([4,5,6])




In [81]:
m=np.vstack([x,y])
print(m)

[[2 3 4]
 [4 5 6]]


In [83]:
n=np.hstack([x,y])
print(n)


[2 3 4 4 5 6]


*Array Creation*

arange, array, copy, empty, empty_like, eye, fromfile, fromfunction, identity, linspace, logspace, mgrid, ogrid, ones, ones_like, r_, zeros, zeros_like

*Conversions*

ndarray.astype, atleast_1d, atleast_2d, atleast_3d, mat

*Manipulations*

array_split, column_stack, concatenate, diagonal, dsplit, dstack, hsplit, hstack, ndarray.item, newaxis, ravel, repeat, reshape, resize, squeeze, swapaxes, take, transpose, vsplit,
vstack

for more , check the link below
https://numpy.org/devdocs/user/quickstart.html
